name: "Check visual regressions"
description: "Makes screenshot from both remote and local storybooks and compare them"

runs:
  using: "composite"
  steps:
    - name: Compare screenshots
      shell: bash
      run: npm run screenshot:compare
      continue-on-error: true

    - name: Notify
      uses: actions/github-script@v8
      with:
        script: |
          const script = require("${{github.action_path}}/script.js");
          script({core, github, context});

    - name: Upload static files as artifact
      id: report-upload
      uses: actions/upload-pages-artifact@v3
      with:
        retention-days: 1
        path: .reg
        name: github-pages

    - name: Deploy to GitHub Pages
      id: report-deployment
      uses: actions/deploy-pages@v4

