name: "Check visual regressions"
description: "Makes screenshot from both remote and local storybooks and compare them"

runs:
  using: "composite"
  steps:
    - name: Compare screenshots
      shell: bash
      run: npm run screenshot:compare
      continue-on-error: true

    - name: Upload static files as artifact
      if: ${{ success() }}
      id: report-upload
      uses: actions/upload-artifact@v4
      with:
        retention-days: 7
        path: .reg
        name: visual-tests-report
        overwrite: true
        include-hidden-files: true

    - name: Notify
      if: ${{ success() }}
      uses: actions/github-script@v8
      with:
        script: |
          const script = require("${{github.action_path}}/script.js");
          const reportUrl = '${{steps.report-upload.outputs.artifact-url}}'
          script({core, github, context}, {reportUrl});

