name: "Check visual regressions"
description: "Makes screenshot from both remote and local storybooks and compare them"

runs:
  using: "composite"
  steps:
    - name: Compare screenshots
      shell: bash
      run: npm run screenshot:compare
      continue-on-error: true

    - name: Notify
      uses: actions/github-script@v8
      with:
        script: |
          const script = require("${{github.action_path}}/script.js");
          script({core, github, context});
